# Generated by Django 3.2 on 2021-05-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.CharField(max_length=5)),
                ('Histology_A_0', models.PositiveIntegerField()),
                ('Histology_B_0', models.PositiveIntegerField()),
                ('Histology_C_0', models.PositiveIntegerField()),
                ('Biomarker_M_0', models.FloatField()),
                ('Biomarker_H_0', models.FloatField()),
                ('Biomarker_T_0', models.FloatField()),
                ('Biomarker_L_0', models.FloatField()),
                ('Biomarker_A_0', models.FloatField()),
                ('Histology_A_12', models.PositiveIntegerField()),
                ('Histology_B_12', models.PositiveIntegerField()),
                ('Histology_C_12', models.PositiveIntegerField()),
                ('Biomarker_M_12', models.FloatField()),
                ('Biomarker_H_12', models.FloatField()),
                ('Biomarker_T_12', models.FloatField()),
                ('Biomarker_L_12', models.FloatField()),
                ('Biomarker_A_12', models.FloatField()),
            ],
        ),
    ]
